name: Build and Deploy

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - uses: pnpm/action-setup@v6

      - name: Install and Build no-fonts 🔧
        run: |
          pnpm i
          pnpm run build:no-fonts
          echo 'board.zash.run.place' > ./dist/CNAME

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Zip the dist folder
        run: |
          zip -r zashboard-lite.zip dist

      - name: Get Version and Date
        id: info
        run: |
          VERSION=$(node -p "require('./package.json').version")
          DATE=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:00')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "date=$DATE" >> $GITHUB_OUTPUT

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: zashboard-lite.zip
          tag_name: v${{ steps.info.outputs.version }}
          name: Zashboard Lite ${{ steps.info.outputs.version }}
          body: "Zashboard Lite v${{ steps.info.outputs.version }} - Customized for MCNext and MCLite  更新于 ${{ steps.info.outputs.date }}"
